services:
  postgres:
    image: postgres:16-alpine
    container_name: codeinsight-db
    environment:
      POSTGRES_DB: codeinsight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CodeInsight@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codeinsight-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/codeinsight
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: CodeInsight@123
      JWT_SECRET: MySuperSecretKeyForCodeInsightAIApplication2026MySuperSecretKey
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: node:20-alpine
    container_name: codeinsight-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend

volumes:
  postgres_data:
