spring:
  application:
    name: backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/codeinsight}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:CodeInsight@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.security: WARN
    root: INFO

jwt:
  secret: ${JWT_SECRET:MySuperSecretKeyForCodeInsightAIApplication2026MySuperSecretKey}
  expiration: 86400000
